import Head from "next/head";
import Image from "next/image";

import Script from "next/script";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {/* ===================================
START LODAER PAGE
    ==================================== */}
        
        <div id="wrapper">
          {/* START CONTENT */}
          <div id="content">
            {/* ===================================
        START THE HEADER
      ==================================== */}
            <header className="default heade-sticky">
              <div className="un-title-page go-back">
                <a href="app-pages.html" className="icon">
                  <i className="ri-arrow-drop-left-line" />
                </a>
                <h1>Create Single</h1>
              </div>
            </header>
            {/* ===================================
        START THE SPACE STICKY
      ==================================== */}
            <div className="space-sticky" />
            {/* ===================================
        START THE UPLOAD FORM
      ==================================== */}
            <section className="un-create-collectibles">
              <div className="form-group upload-form">
                <h2>Upload file</h2>
                <p>Choose your file to upload</p>
                <div className="upload-input-form">
                  <input type="file" />
                  <div className="content-input">
                    <div className="icon">
                      <i className="ri-upload-cloud-line" />
                    </div>
                    <span>PNG, GIF, WEBP, MP4 or MP3. Max 50mb.</span>
                  </div>
                </div>
                <div className="uploaded-image mt-3">
                  <picture>
                    <source srcSet="images/other/1.webp" type="image/webp" />
                    <img src="images/other/1.jpg" alt="" />
                  </picture>
                  <button type="clear" className="btn icon-clear">
                    <i className="ri-delete-bin-line" />
                  </button>
                </div>
              </div>
              <div className="form-group">
                <label>Item Name</label>
                <input
                  type="text"
                  className="form-control"
                  placeholder='e. g. "LUCKY_WATCHER"'
                />
              </div>
              <div className="form-group">
                <label>
                  Description <span className="size-11">(Optional)</span>
                </label>
                <textarea
                  className="form-control"
                  rows={3}
                  placeholder='e. g. "After purchasing you’ll be able to get ..."'
                  defaultValue={""}
                />
              </div>
            </section>
            {/* ===================================
        START PUT ON SALE
      ==================================== */}
            <section className="un-activity-toggle">
              <nav className="nav flex-column">
                <div className="nav-link border-0 px-0 mb-0 pt-1">
                  <div className="text">
                    <h2>Put on sale</h2>
                    <p>You’ll receive bids on this item</p>
                  </div>
                  <label
                    className="switch_toggle toggle_lg"
                    htmlFor="swithDefault"
                  >
                    <input
                      type="checkbox"
                      defaultChecked=""
                      id="swithDefault"
                    />
                    <span className="handle" />
                  </label>
                </div>
                <div className="nav-link border-0 px-0 mb-0">
                  <div className="text">
                    <h2>Instant sale price</h2>
                    <p>
                      Enter the price for which the item will be instantly sold
                    </p>
                  </div>
                  <label
                    className="switch_toggle toggle_lg"
                    htmlFor="swithDefault2"
                  >
                    <input type="checkbox" id="swithDefault2" />
                    <span className="handle" />
                  </label>
                </div>
                <div className="nav-link border-0 px-0 mb-0">
                  <div className="text">
                    <h2>Unlock once purchased</h2>
                    <p>Content will be unlocked after successful transaction</p>
                  </div>
                  <label
                    className="switch_toggle toggle_lg"
                    htmlFor="swithDefault3"
                  >
                    <input type="checkbox" id="swithDefault3" />
                    <span className="handle" />
                  </label>
                </div>
              </nav>
            </section>
            {/* ===================================
        START THE SPACE STICKY -FOOTER
      ==================================== */}
            {/* space-sticky-footer */}
            <div className="space-sticky-footer" />
            {/* ===================================
        START THE FOOTER - BUTTONS
      ==================================== */}
            <footer className="footer-pages-forms">
              <div className="content">
                <div className="update-auto">
                  <div className="auto-saving">
                    <div className="loader-items">
                      <div className="lds-spinner">
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                        <div />
                      </div>
                    </div>
                    <span>auto-saving</span>
                  </div>
                </div>
                <a
                  href="page-put-on-marketplace.html"
                  className="btn btn-bid-items"
                >
                  <p>Create item</p>
                  <div className="ico">
                    <i className="ri-arrow-drop-right-line" />
                  </div>
                </a>
              </div>
            </footer>
          </div>
        </div>
        {/* ===================================
START THE EXTERNAL OPEN MODAL
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllOtherOpen"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header border-0" />
              <div className="modal-body pt-0">
                <div className="content-alert-actions">
                  <div className="margin-b-20">
                    <h2>This page will open another application.</h2>
                  </div>
                  <div className="action-links">
                    <button
                      type="button"
                      className="btn border color-text rounded-pill margin-r-20"
                    >
                      Cancel
                    </button>
                    <a
                      href="javascript: void(0)"
                      className="btn bg-primary text-white rounded-pill"
                    >
                      Open
                    </a>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL UPLOAD
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllUploadItem"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Upload Item</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item text-center">
                  <p>
                    Choose <span>"Single"</span> if you want your collectible to
                    be one of a kind or
                    <span>"Multiple"</span>
                    if you want to sell one collectible multiple times
                  </p>
                  <div className="grid_buttonUpload">
                    <a
                      href="page-create-single.html"
                      className="btn btn-create bg-primary text-white margin-b-20"
                    >
                      Create Single
                    </a>
                    <a
                      href="page-create-multi.html"
                      className="btn btn-create bg-white border border-solid border-snow text-dark"
                    >
                      Create Multiple
                    </a>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL ADD ETH
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllAddETH"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Add ETH to your wallet</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item">
                  <p className="text-center">
                    Select one of the options to deposit <br /> ETH to your
                    wallet
                  </p>
                  <div className="un-navMenu-default margin-t-30 p-0">
                    <ul className="nav flex-column">
                      <li className="nav-item mb-3">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-exchange-box-line" />
                            </div>
                            <h3 className="link-title">
                              Deposit from an exchange
                            </h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item mb-0">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-bank-card-line" />
                            </div>
                            <h3 className="link-title">Buy with card</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL SIDEBAR MENU - CONNECTED
    ==================================== */}
       
        {/* ===================================
START THE MODAL SIDEBAR MENU - guest
    ==================================== */}
        <div
          className="modal sidebarMenu -left -guest fade"
          id="mdllSidebar-guest"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-scrollable">
            <div className="modal-content">
              <div className="modal-header">
                <div className="welcome_em">
                  <h2>
                    Welcome to Unic<span>.</span>
                  </h2>
                  <p>
                    Connect wallet to browse, Buy, Sell, and create NFTs items.
                  </p>
                  <a
                    href="page-connect-wallet.html"
                    className="btn btn-md-size bg-primary text-white rounded-pill"
                  >
                    Connect wallet
                  </a>
                </div>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <ul className="nav flex-column -active-links">
                  <li className="nav-item">
                    <a className="nav-link" href="homepage.html">
                      <div className="icon_current">
                        <i className="ri-compass-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-compass-fill" />
                      </div>
                      <span className="title_link">Discover</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-homes.html">
                      <div className="icon_current">
                        <i className="ri-home-5-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-home-5-fill" />
                      </div>
                      <span className="title_link">Home Styles</span>
                      <span className="xs-badge">8</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-pages.html">
                      <div className="icon_current">
                        <i className="ri-pages-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-pages-fill" />
                      </div>
                      <span className="title_link">Page Packs</span>
                      <div className="badge-circle">
                        <span className="doted_item" />
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-components.html">
                      <div className="icon_current">
                        <i className="ri-layout-2-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-layout-2-fill" />
                      </div>
                      <span className="title_link">Components</span>
                    </a>
                  </li>
                  <label className="title__label">other</label>
                  <li className="nav-item">
                    <a className="nav-link" href="page-help.html">
                      <div className="icon_current">
                        <i className="ri-questionnaire-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-questionnaire-fill" />
                      </div>
                      <span className="title_link">Help Center</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="page-about.html">
                      <div className="icon_current">
                        <i className="ri-file-info-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-file-info-fill" />
                      </div>
                      <span className="title_link">About Unic.</span>
                    </a>
                  </li>
                </ul>
              </div>
              <div className="modal-footer">
                <div className="em_darkMode_menu">
                  <label className="text" htmlFor="switchDark2">
                    <h3>Dark Mode</h3>
                    <p>Browsing in night mode</p>
                  </label>
                  <label
                    className="switch_toggle toggle_lg theme-switch"
                    htmlFor="switchDark2"
                  >
                    <input
                      type="checkbox"
                      className="switchDarkMode theme-switch"
                      id="switchDark2"
                      aria-describedby="switchDark2"
                    />
                    <span className="handle" />
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE SHARE PROFILE MODAL
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllShareProfile"
          tabIndex={-1}
          aria-labelledby="modalShareProfile"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <div className="item-shared">
                  <div className="image-items">
                    <picture>
                      <source
                        srcSet="images/avatar/22.webp"
                        type="image/webp"
                      />
                      <img
                        className="user-img"
                        src="images/avatar/22.jpg"
                        alt=""
                      />
                    </picture>
                  </div>
                  <div className="txt">
                    <h1>Camillo Ferrari</h1>
                    <p>unic.com</p>
                  </div>
                </div>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-share-socials">
                  <div className="un-navMenu-default p-0">
                    <ul className="nav flex-column">
                      <li className="nav-item">
                        <button type="button" className="btn nav-link bg-snow">
                          <div className="item-content-link">
                            <h3 className="link-title">Copy</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-file-copy-2-line" />
                            </div>
                          </div>
                        </button>
                      </li>
                    </ul>
                    <div className="sub-title-pkg">
                      <h2>Social Networks</h2>
                    </div>
                    <ul className="nav flex-column">
                      <li className="nav-item">
                        <a
                          className="nav-link facebook"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/facebook.svg" alt="" />
                            </div>
                            <h3 className="link-title">Facebook</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link twitter"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/twitter.svg" alt="" />
                            </div>
                            <h3 className="link-title">Twitter</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link instrgrame"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/instagram.svg" alt="" />
                            </div>
                            <h3 className="link-title">Instrgrame</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link whatsapp"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/whatsapp.svg" alt="" />
                            </div>
                            <h3 className="link-title">WhatsApp</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE SHARE NFT MODAL
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllShareCollectibles"
          tabIndex={-1}
          aria-labelledby="modalShareCollectibles"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <div className="item-shared">
                  <div className="image-items">
                    <picture>
                      <source srcSet="images/other/1.webp" type="image/webp" />
                      <img
                        className="user-img"
                        src="images/other/1.jpg"
                        alt=""
                      />
                    </picture>
                  </div>
                  <div className="txt">
                    <h1>Galaxy on Earth</h1>
                    <p>unic.com</p>
                  </div>
                </div>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-share-socials">
                  <div className="un-navMenu-default p-0">
                    <ul className="nav flex-column">
                      <li className="nav-item">
                        <button type="button" className="btn nav-link bg-snow ">
                          <div className="item-content-link">
                            <h3 className="link-title">Copy</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-file-copy-2-line" />
                            </div>
                          </div>
                        </button>
                      </li>
                    </ul>
                    <div className="sub-title-pkg">
                      <h2>Social Networks</h2>
                    </div>
                    <ul className="nav flex-column">
                      <li className="nav-item">
                        <a
                          className="nav-link facebook"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/facebook.svg" alt="" />
                            </div>
                            <h3 className="link-title">Facebook</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link twitter"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/twitter.svg" alt="" />
                            </div>
                            <h3 className="link-title">Twitter</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link instrgrame"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/instagram.svg" alt="" />
                            </div>
                            <h3 className="link-title">Instrgrame</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item">
                        <a
                          className="nav-link whatsapp"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon-svg">
                              <img src="images/icons/whatsapp.svg" alt="" />
                            </div>
                            <h3 className="link-title">WhatsApp</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START STATUS CONNECTION
    ==================================== */}
        <div className="d-flex justify-content-center">
          <div
            className="toast status-connection"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          />
        </div>
        {/* JS FILES */}
        {/* PWA APP SERVICE REGISTRATION AND WORKS JS */}
      </>

      <Script src="assets/vendors/zuck_stories/zuck.min.js"></Script>
      <Script src="assets/vendors/smoothscroll/smoothscroll.min.js"></Script>
      <Script src="assets/vendors/swiper/swiper-bundle.min.js"></Script>
      <Script src="assets/vendors/nouislider/nouislider.min.js"></Script>
      <Script src="assets/vendors/nouislider/wNumb.min.js"></Script>
      <Script src="assets/js/bootstrap.bundle.min.js"></Script>
      <Script src="assets/js/pwa-services.js"></Script>
      <Script src="assets/js/custom.js"></Script>
    </>
  );
}
