import Head from "next/head";
import Image from "next/image";

import Script from "next/script";
import Header from "@/components/Header";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        {/* ===================================
START LODAER PAGE
    ==================================== */}
        {/* <section className="loader-page" id="loaderPage">
          <div className="spinner_flash" />
        </section> */}
        {/* START WRAPPER */}
        <div id="wrapper">
          {/* START CONTENT */}
          <div id="content">
            {/* ===================================
        START THE HEADER
      ==================================== */}

            {/* ===================================
        START THE SPACE STICKY
      ==================================== */}
            <div className="space-sticky" />
            {/* ===================================
        START THE STORIES SECTION
      ==================================== */}
            <section className="margin-t-20 margin-b-10 stories-section">
              {/* DISPLAY STRORIES */}
              <div className="display-stories">
                {/* SWIPER */}
                <div className="swiper myStories">
                  <div className="swiper-wrapper wrapper-stories" id="stories">
                    {/* MY STORY */}
                    <div className="swiper-slide space">
                      <button
                        type="button"
                        className="btn add-my-story"
                        data-bs-toggle="modal"
                        data-bs-target="#mdllAddStory"
                      >
                        <div className="my_img">
                          <img src="images/avatar/11.jpg" alt="my story" />
                          <div className="icon">
                            <i className="ri-add-fill" />
                          </div>
                        </div>
                        <div className="display-text">
                          <span>My Story</span>
                        </div>
                      </button>
                    </div>
                    {/* HERE -> ITEMS -> AUTOMATICALLY BY JAVASCRIPT */}
                  </div>
                </div>
              </div>
            </section>
            {/* ===================================
        START THE BORDER SECTIONS
      ==================================== */}
            <div className="border-sections-home" />
            {/* ===================================
        START THE RANDOM NFTS
      ==================================== */}
            <section className="unSwiper-cards margin-t-20">
              {/* un-title-default */}
              <div className="un-title-default">
                <div className="text">
                  <h2>Discover</h2>
                  <p>Be on the lookout for the latest NFTs</p>
                </div>
                <div className="un-block-right">
                  <a
                    href="page-search-random.html"
                    className="icon-back"
                    aria-label="iconBtn"
                  >
                    <i className="ri-arrow-drop-right-line" />
                  </a>
                </div>
              </div>
              <div className="discover-nft-random margin-t-20">
                <div className="content-NFTs-body">
                  {/* item-card-nft */}
                  <div className="item-card-nft">
                    <picture>
                      <source srcSet="images/other/14.jpg" type="image/webp" />
                      <img
                        className="big-image"
                        src="images/other/14.jpg"
                        alt=""
                      />
                    </picture>
                    <div className="counterdown">
                      <span>08H</span>
                      <span>38M</span>
                      <span>16S</span>
                    </div>
                    <div className="btn-like-click">
                      <div className="btnLike">
                        <input type="checkbox" defaultChecked="" />
                        <span className="count-likes">197</span>
                        <i className="ri-heart-3-line" />
                      </div>
                    </div>
                    <a
                      href="page-collectibles-details.html"
                      className="un-info-card"
                    >
                      <div className="block-left">
                        <h4>Dark Side of Me</h4>
                        <div className="user">
                          <picture>
                            <source
                              srcSet="images/avatar/19.jpg"
                              type="image/webp"
                            />
                            <img
                              className="img-avatar"
                              src="images/avatar/19.jpg"
                              alt=""
                            />
                          </picture>
                          <h5>Julian Co.</h5>
                        </div>
                      </div>
                      <div className="block-right">
                        <h6>Starting Bid</h6>
                        <p>
                          <span>($3,650)</span>
                          1.50 ETH
                        </p>
                      </div>
                    </a>
                  </div>
                  {/* item-sm-card-NFTs */}
                  <a
                    href="page-collectibles-details.html"
                    className="item-sm-card-NFTs"
                  >
                    <div className="cover-image">
                      <picture>
                        <source
                          srcSet="images/other/30.jpg"
                          type="image/webp"
                        />
                        <img
                          className="big-image"
                          src="images/other/30.jpg"
                          alt=""
                        />
                      </picture>
                      <div className="content-text">
                        <div className="btn-like-click">
                          <div className="btnLike">
                            <input type="checkbox" />
                            <span className="count-likes">14</span>
                            <i className="ri-heart-3-line" />
                          </div>
                        </div>
                      </div>
                      <div className="user-text">
                        <div className="user-avatar">
                          <picture>
                            <source
                              srcSet="images/avatar/10.jpg"
                              type="image/webp"
                            />
                            <img
                              className="sm-user"
                              src="images/avatar/10.jpg"
                              alt=""
                            />
                          </picture>
                          <span>Camillo</span>
                        </div>
                        <div className="number-eth">
                          <span className="main-price">1.50 ETH</span>
                          <span>($3,650)</span>
                        </div>
                      </div>
                    </div>
                  </a>
                  {/* item-sm-card-NFTs */}
                  <a
                    href="page-collectibles-details.html"
                    className="item-sm-card-NFTs"
                  >
                    <div className="cover-image">
                      <picture>
                        <source
                          srcSet="images/other/19.jpg"
                          type="image/webp"
                        />
                        <img
                          className="big-image"
                          src="images/other/19.jpg"
                          alt=""
                        />
                      </picture>
                      <div className="content-text">
                        <div className="icon-type">
                          <i className="ri-vidicon-line" />
                        </div>
                        <div className="btn-like-click">
                          <div className="btnLike">
                            <input type="checkbox" />
                            <span className="count-likes">0</span>
                            <i className="ri-heart-3-line" />
                          </div>
                        </div>
                      </div>
                      <div className="user-text">
                        <div className="user-avatar">
                          <picture>
                            <source
                              srcSet="images/avatar/14.jpg"
                              type="image/webp"
                            />
                            <img
                              className="sm-user"
                              src="images/avatar/14.jpg"
                              alt=""
                            />
                          </picture>
                          <span>Julian Co.</span>
                        </div>
                        <div className="number-eth">
                          <span className="main-price">1.50 ETH</span>
                          <span>($3,650)</span>
                        </div>
                      </div>
                    </div>
                  </a>
                  {/* item-sm-card-NFTs */}
                  <a
                    href="page-collectibles-details.html"
                    className="item-sm-card-NFTs"
                  >
                    <div className="cover-image">
                      <picture>
                        <source
                          srcSet="images/other/24.jpg"
                          type="image/webp"
                        />
                        <img
                          className="big-image"
                          src="images/other/24.jpg"
                          alt=""
                        />
                      </picture>
                      <div className="content-text">
                        <div className="btn-like-click">
                          <div className="btnLike">
                            <input type="checkbox" defaultChecked="" />
                            <span className="count-likes">42</span>
                            <i className="ri-heart-3-line" />
                          </div>
                        </div>
                      </div>
                      <div className="user-text">
                        <div className="user-avatar">
                          <picture>
                            <source
                              srcSet="images/avatar/10.jpg"
                              type="image/webp"
                            />
                            <img
                              className="sm-user"
                              src="images/avatar/10.jpg"
                              alt=""
                            />
                          </picture>
                          <span>Camillo</span>
                        </div>
                        <div className="number-eth">
                          <span className="main-price">1.50 ETH</span>
                          <span>($3,650)</span>
                        </div>
                      </div>
                    </div>
                  </a>
                  {/* item-sm-card-NFTs */}
                  <a
                    href="page-collectibles-details.html"
                    className="item-sm-card-NFTs"
                  >
                    <div className="cover-image">
                      <picture>
                        <source
                          srcSet="images/other/16.jpg"
                          type="image/webp"
                        />
                        <img
                          className="big-image"
                          src="images/other/16.jpg"
                          alt=""
                        />
                      </picture>
                      <div className="content-text">
                        <div className="icon-type">
                          <i className="ri-vidicon-line" />
                        </div>
                        <div className="btn-like-click">
                          <div className="btnLike">
                            <input type="checkbox" />
                            <span className="count-likes">27</span>
                            <i className="ri-heart-3-line" />
                          </div>
                        </div>
                      </div>
                      <div className="user-text">
                        <div className="user-avatar">
                          <picture>
                            <source
                              srcSet="images/avatar/14.jpg"
                              type="image/webp"
                            />
                            <img
                              className="sm-user"
                              src="images/avatar/14.jpg"
                              alt=""
                            />
                          </picture>
                          <span>Julian Co.</span>
                        </div>
                        <div className="number-eth">
                          <span className="main-price">1.50 ETH</span>
                          <span>($3,650)</span>
                        </div>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            </section>
            
            <section className="un-section-seller margin-y-20">
              {/* un-title-default */}
              <div className="un-title-default">
                <div className="text">
                  <h2>Best Sellers</h2>
                  <p>Best seller of this week's NFTs</p>
                </div>
                <div className="un-block-right">
                  <a
                    href="page-best-seller.html"
                    className="icon-back"
                    aria-label="iconBtn"
                  >
                    <i className="ri-arrow-drop-right-line" />
                  </a>
                </div>
              </div>
              {/* un-block-auther */}
              <div className="un-block-creators margin-t-20">
                {/* Swiper */}
                <div className="swiper swiperCreators">
                  <div className="swiper-wrapper">
                    <div className="swiper-slide">
                      {/* un-item-seller */}
                      <a
                        href="page-creator-profile.html"
                        className="un-item-seller"
                      >
                        <div className="number">01</div>
                        <div className="media-profile">
                          <figure className="image-avatar">
                            <picture>
                              <source
                                srcSet="images/avatar/22.jpg"
                                type="image/webp"
                              />
                              <img src="images/avatar/22.jpg" alt="" />
                            </picture>
                            <div className="icon-verify">
                              <i className="ri-checkbox-circle-fill" />
                            </div>
                          </figure>
                          <div className="text">
                            <h3>MelonPixel⚡</h3>
                            <p>19.4 ETH</p>
                          </div>
                        </div>
                      </a>
                    </div>
                    <div className="swiper-slide">
                      {/* un-item-seller */}
                      <a
                        href="page-creator-profile.html"
                        className="un-item-seller"
                      >
                        <div className="number">02</div>
                        <div className="media-profile">
                          <figure className="image-avatar">
                            <picture>
                              <source
                                srcSet="images/avatar/18.jpg"
                                type="image/webp"
                              />
                              <img src="images/avatar/18.jpg" alt="" />
                            </picture>
                            <div className="icon-verify">
                              <i className="ri-checkbox-circle-fill" />
                            </div>
                          </figure>
                          <div className="text">
                            <h3>Camillo Ferrari</h3>
                            <p>5.3 ETH</p>
                          </div>
                        </div>
                      </a>
                    </div>
                    <div className="swiper-slide">
                      {/* un-item-seller */}
                      <a
                        href="page-creator-profile.html"
                        className="un-item-seller"
                      >
                        <div className="number">03</div>
                        <div className="media-profile">
                          <figure className="image-avatar">
                            <picture>
                              <source
                                srcSet="images/avatar/14.jpg"
                                type="image/webp"
                              />
                              <img src="images/avatar/14.jpg" alt="" />
                            </picture>
                            <div className="icon-verify">
                              <i className="ri-checkbox-circle-fill" />
                            </div>
                          </figure>
                          <div className="text">
                            <h3>🚀 Pingu</h3>
                            <p>3.9 ETH</p>
                          </div>
                        </div>
                      </a>
                    </div>
                    <div className="swiper-slide">
                      {/* un-item-seller */}
                      <a
                        href="page-creator-profile.html"
                        className="un-item-seller"
                      >
                        <div className="number">04</div>
                        <div className="media-profile">
                          <figure className="image-avatar">
                            <picture>
                              <source
                                srcSet="images/avatar/5.jpg"
                                type="image/webp"
                              />
                              <img src="images/avatar/5.png" alt="" />
                            </picture>
                            <div className="icon-verify">
                              <i className="ri-checkbox-circle-fill" />
                            </div>
                          </figure>
                          <div className="text">
                            <h3>Julian Co.</h3>
                            <p>2.8 ETH</p>
                          </div>
                        </div>
                      </a>
                    </div>
                    <div className="swiper-slide">
                      {/* un-item-seller */}
                      <a
                        href="page-creator-profile.html"
                        className="un-item-seller"
                      >
                        <div className="number">05</div>
                        <div className="media-profile">
                          <figure className="image-avatar">
                            <picture>
                              <source
                                srcSet="images/avatar/13.jpg"
                                type="image/webp"
                              />
                              <img src="images/avatar/13.jpg" alt="" />
                            </picture>
                            <div className="icon-verify">
                              <i className="ri-checkbox-circle-fill" />
                            </div>
                          </figure>
                          <div className="text">
                            <h3>Tito_Calab</h3>
                            <p>2.7 ETH</p>
                          </div>
                        </div>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </section>
           
            <div className="border-sections-home" />

            <section className="margin-t-20 unList-creatores">
              <div className="un-title-default">
                <div className="text">
                  <h2>Creators</h2>
                  <p>You can follow many Creators</p>
                </div>
                <div className="un-block-right">
                  <a
                    href="page-creators.html"
                    className="icon-back"
                    aria-label="iconBtn"
                  >
                    <i className="ri-arrow-drop-right-line" />
                  </a>
                </div>
              </div>
              <div className="content-list-creatores">
                <ul className="nav flex-column">
                  <li className="nav-item">
                    <a className="nav-link" href="page-creator-profile.html">
                      <div className="item-user-img">
                        <picture>
                          <source
                            srcSet="images/avatar/13.jpg"
                            type="image/webp"
                          />
                          <img
                            className="avt-img"
                            src="images/avatar/13.jpg"
                            alt=""
                          />
                        </picture>
                        <div className="txt-user">
                          <h5>Richard Noga</h5>
                          <p>$9,500.32</p>
                        </div>
                      </div>
                      <div className="other-option">
                        <div className="color-text rounded-pill bg-snow btn-xs-size">
                          44 Item
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="page-creator-profile.html">
                      <div className="item-user-img">
                        <picture>
                          <source
                            srcSet="images/avatar/7.jpg"
                            type="image/webp"
                          />
                          <img
                            className="avt-img"
                            src="images/avatar/7.jpg"
                            alt=""
                          />
                        </picture>
                        <div className="txt-user">
                          <h5>Tito_Calab</h5>
                          <p>$8,382.32</p>
                        </div>
                      </div>
                      <div className="other-option">
                        <div className="color-text rounded-pill bg-snow btn-xs-size">
                          37 Item
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="page-creator-profile.html">
                      <div className="item-user-img">
                        <picture>
                          <source
                            srcSet="images/avatar/4.jpg"
                            type="image/webp"
                          />
                          <img
                            className="avt-img"
                            src="images/avatar/4.jpg"
                            alt=""
                          />
                        </picture>
                        <div className="txt-user">
                          <h5>Settimio Loggia</h5>
                          <p>$6,920.00</p>
                        </div>
                      </div>
                      <div className="other-option">
                        <div className="color-text rounded-pill bg-snow btn-xs-size">
                          30 Item
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="page-creator-profile.html">
                      <div className="item-user-img">
                        <picture>
                          <source
                            srcSet="images/avatar/1.jpg"
                            type="image/webp"
                          />
                          <img
                            className="avt-img"
                            src="images/avatar/1.jpg"
                            alt="user"
                          />
                        </picture>
                        <div className="txt-user">
                          <h5>Vinicius O.</h5>
                          <p>$4,500.32</p>
                        </div>
                      </div>
                      <div className="other-option">
                        <div className="color-text rounded-pill bg-snow btn-xs-size">
                          20 Item
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </section>
          </div>

        
        </div>
        {/* ===================================
START THE MODAL UPLOAD
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllUploadItem"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Upload Item</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item text-center">
                  <p>
                    Choose <span>"Single"</span> if you want your collectible to
                    be one of a kind or
                    <span>"Multiple"</span>
                    if you want to sell one collectible multiple times
                  </p>
                  <div className="grid_buttonUpload">
                    <a
                      href="page-create-single.html"
                      className="btn btn-create bg-primary text-white margin-b-20"
                    >
                      Create Single
                    </a>
                    <a
                      href="page-create-multi.html"
                      className="btn btn-create bg-white border border-solid border-snow text-dark"
                    >
                      Create Multiple
                    </a>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL ADD ETH
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllAddETH"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Add ETH to your wallet</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item">
                  <p className="text-center">
                    Select one of the options to deposit <br /> ETH to your
                    wallet
                  </p>
                  <div className="un-navMenu-default margin-t-30 p-0">
                    <ul className="nav flex-column">
                      <li className="nav-item mb-3">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-exchange-box-line" />
                            </div>
                            <h3 className="link-title">
                              Deposit from an exchange
                            </h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item mb-0">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-bank-card-line" />
                            </div>
                            <h3 className="link-title">Buy with card</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL SIDEBAR MENU - CONNECTED
    ==================================== */}
        
        {/* ===================================
START THE MODAL SIDEBAR MENU - guest
    ==================================== */}
        <div
          className="modal sidebarMenu -left -guest fade"
          id="mdllSidebar-guest"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-scrollable">
            <div className="modal-content">
              <div className="modal-header">
                <div className="welcome_em">
                  <h2>
                    Welcome to Unic<span>.</span>
                  </h2>
                  <p>
                    Connect wallet to browse, Buy, Sell, and create NFTs items.
                  </p>
                  <a
                    href="page-connect-wallet.html"
                    className="btn btn-md-size bg-primary text-white rounded-pill"
                  >
                    Connect wallet
                  </a>
                </div>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <ul className="nav flex-column -active-links">
                  <li className="nav-item">
                    <a className="nav-link" href="homepage.html">
                      <div className="icon_current">
                        <i className="ri-compass-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-compass-fill" />
                      </div>
                      <span className="title_link">Discover</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-homes.html">
                      <div className="icon_current">
                        <i className="ri-home-5-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-home-5-fill" />
                      </div>
                      <span className="title_link">Home Styles</span>
                      <span className="xs-badge">8</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-pages.html">
                      <div className="icon_current">
                        <i className="ri-pages-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-pages-fill" />
                      </div>
                      <span className="title_link">Page Packs</span>
                      <div className="badge-circle">
                        <span className="doted_item" />
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="app-components.html">
                      <div className="icon_current">
                        <i className="ri-layout-2-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-layout-2-fill" />
                      </div>
                      <span className="title_link">Components</span>
                    </a>
                  </li>
                  <label className="title__label">other</label>
                  <li className="nav-item">
                    <a className="nav-link" href="page-help.html">
                      <div className="icon_current">
                        <i className="ri-questionnaire-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-questionnaire-fill" />
                      </div>
                      <span className="title_link">Help Center</span>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="page-about.html">
                      <div className="icon_current">
                        <i className="ri-file-info-line" />
                      </div>
                      <div className="icon_active">
                        <i className="ri-file-info-fill" />
                      </div>
                      <span className="title_link">About Unic.</span>
                    </a>
                  </li>
                </ul>
              </div>
              <div className="modal-footer">
                <div className="em_darkMode_menu">
                  <label className="text" htmlFor="switchDark2">
                    <h3>Dark Mode</h3>
                    <p>Browsing in night mode</p>
                  </label>
                  <label
                    className="switch_toggle toggle_lg theme-switch"
                    htmlFor="switchDark2"
                  >
                    <input
                      type="checkbox"
                      className="switchDarkMode theme-switch"
                      id="switchDark2"
                      aria-describedby="switchDark2"
                    />
                    <span className="handle" />
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE CREATE STORY MODAL
    ==================================== */}
        <div
          className="modal sidebarMenu -left --fullScreen modal-filter fade"
          id="mdllAddStory"
          tabIndex={-1}
          aria-labelledby="sidebarMenuLabel3"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-scrollable">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Create Story</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="un-create-collectibles bg-white p-0">
                  <div className="form-group upload-form">
                    <h2>Upload file</h2>
                    <p>Choose your file to upload</p>
                    <div className="upload-input-form">
                      <input type="file" />
                      <div className="content-input">
                        <div className="icon">
                          <i className="ri-upload-cloud-line" />
                        </div>
                        <span>PNG, GIF, JPG, MP4 . Max 5 mb.</span>
                      </div>
                    </div>
                  </div>
                  <div className="form-group icon-right">
                    <label>Add Link</label>
                    <div className="input_group">
                      <input
                        type="url"
                        className="form-control"
                        placeholder='e. g. "www.example.com"'
                      />
                      <div className="icon">
                        <i className="ri-link" />
                      </div>
                    </div>
                  </div>
                  <div className="form-group">
                    <label>Link Text</label>
                    <div className="inpust_group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder='e. g. "INSTALL APP"'
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer justify-content-center border-0 pt-2">
                <div className="footer-pages-forms">
                  <div className="content">
                    <div className="links-clear-data">
                      <button
                        type="button"
                        className="btn link-clear"
                        data-bs-toggle="modal"
                        data-bs-dismiss="modal"
                      >
                        <i className="ri-close-circle-line" />
                        <span>Cancel</span>
                      </button>
                    </div>
                    <a
                      href="page-home-stories.html"
                      className="btn btn-bid-items"
                    >
                      <p>Create Story</p>
                      <div className="ico">
                        <i className="ri-arrow-drop-right-line" />
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START STATUS CONNECTION
    ==================================== */}
        <div className="d-flex justify-content-center">
          <div
            className="toast status-connection"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          />
        </div>
        {/* JS FILES */}
        {/* PWA APP SERVICE REGISTRATION AND WORKS JS */}
      </>
    </>
  );
}
