import Head from "next/head";
import Image from "next/image";

import Script from "next/script";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
         
      </Head>

      <>
        {/* ===================================
START LODAER PAGE
    ==================================== */}
       
       
        <div id="wrapper">
          {/* START CONTENT */}
          <div id="content">
            {/* ===================================
        START THE HEADER
      ==================================== */}
            <header className="default heade-sticky">
              <div className="un-title-page go-back">
                <a href="app-components.html" className="icon">
                  <i className="ri-arrow-drop-left-line" />
                </a>
              </div>
            </header>
            {/* ===================================
        START THE SPACE STICKY
      ==================================== */}
            <div className="space-sticky" />
            {/* ===================================
         START THE CONTENT
      ==================================== */}
            <section className="un-page-components">
              <div className="un-title-default">
                <div className="text">
                  <h2>Scroll Top</h2>
                  <p>
                    To change the location of the item add class{" "}
                    <code>.--center</code> or <code>.--left</code>
                    to <code>.scroll-top</code>
                  </p>
                </div>
              </div>
              <div className="content-comp p-0">
                <div className="space-items" />
                <div className="bg-white padding-20">
                  <p className="size-14 color-tex">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Convallis posuere morbi leo urna molestie at
                    elementum. Nunc eget lorem dolor sed viverra ipsum. Id
                    venenatis a condimentum vitae sapien. At ultrices mi tempus
                    imperdiet. Neque aliquam vestibulum morbi blandit. Porttitor
                    lacus luctus accumsan tortor posuere ac. Leo duis ut diam
                    quam nulla porttitor massa. Sem integer vitae justo eget
                    magna. Vulputate sapien nec sagittis aliquam malesuada. Est
                    velit egestas dui id ornare arcu odio ut. Quis commodo odio
                    aenean sed adipiscing diam donec adipiscing. Sit amet justo
                    donec enim diam. Sit amet porttitor eget dolor morbi non.
                    Tortor vitae purus faucibus ornare suspendisse sed nisi
                    lacus sed. Auctor augue mauris augue neque gravida in. Massa
                    massa ultricies mi quis hendrerit dolor magna. Felis
                    bibendum ut tristique et. Tristique senectus et netus et
                    malesuada fames ac turpis. Tempus urna et pharetra pharetra.
                  </p>
                  <p className="size-14 color-tex">
                    Cras ornare arcu dui vivamus arcu felis bibendum ut. Rhoncus
                    est pellentesque elit ullamcorper dignissim cras tincidunt
                    lobortis feugiat. Est ullamcorper eget nulla facilisi etiam.
                    Mauris in aliquam sem fringilla ut morbi tincidunt. Sapien
                    et ligula ullamcorper malesuada proin libero. Et molestie ac
                    feugiat sed lectus. Sed sed risus pretium quam vulputate
                    dignissim suspendisse in est. Congue mauris rhoncus aenean
                    vel elit scelerisque. Cursus in hac habitasse platea
                    dictumst quisque sagittis. Vestibulum mattis ullamcorper
                    velit sed ullamcorper morbi tincidunt ornare. Laoreet sit
                    amet cursus sit amet dictum sit. Augue ut lectus arcu
                    bibendum. Vulputate ut pharetra sit amet aliquam id diam
                    maecenas ultricies. Et magnis dis parturient montes.
                    Eleifend mi in nulla posuere sollicitudin aliquam. Tellus in
                    metus vulputate eu scelerisque felis imperdiet proin. Amet
                    nulla facilisi morbi tempus iaculis urna id. Cras semper
                    auctor neque vitae tempus quam.
                  </p>
                  <p className="size-14 color-tex">
                    Etiam sit amet nisl purus in mollis. Amet dictum sit amet
                    justo donec. Fringilla phasellus faucibus scelerisque
                    eleifend donec. Tortor posuere ac ut consequat semper. Sit
                    amet volutpat consequat mauris nunc congue nisi vitae
                    suscipit. Gravida rutrum quisque non tellus orci ac auctor
                    augue. Ultrices gravida dictum fusce ut. Scelerisque varius
                    morbi enim nunc faucibus. Morbi tempus iaculis urna id.
                    Rutrum tellus pellentesque eu tincidunt tortor.
                  </p>
                  <p className="size-14 color-tex">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Convallis posuere morbi leo urna molestie at
                    elementum. Nunc eget lorem dolor sed viverra ipsum. Id
                    venenatis a condimentum vitae sapien. At ultrices mi tempus
                    imperdiet. Neque aliquam vestibulum morbi blandit. Porttitor
                    lacus luctus accumsan tortor posuere ac. Leo duis ut diam
                    quam nulla porttitor massa. Sem integer vitae justo eget
                    magna. Vulputate sapien nec sagittis aliquam malesuada. Est
                    velit egestas dui id ornare arcu odio ut. Quis commodo odio
                    aenean sed adipiscing diam donec adipiscing. Sit amet justo
                    donec enim diam. Sit amet porttitor eget dolor morbi non.
                    Tortor vitae purus faucibus ornare suspendisse sed nisi
                    lacus sed. Auctor augue mauris augue neque gravida in. Massa
                    massa ultricies mi quis hendrerit dolor magna. Felis
                    bibendum ut tristique et. Tristique senectus et netus et
                    malesuada fames ac turpis. Tempus urna et pharetra pharetra.
                  </p>
                  <p className="size-14 color-tex">
                    Cras ornare arcu dui vivamus arcu felis bibendum ut. Rhoncus
                    est pellentesque elit ullamcorper dignissim cras tincidunt
                    lobortis feugiat. Est ullamcorper eget nulla facilisi etiam.
                    Mauris in aliquam sem fringilla ut morbi tincidunt. Sapien
                    et ligula ullamcorper malesuada proin libero. Et molestie ac
                    feugiat sed lectus. Sed sed risus pretium quam vulputate
                    dignissim suspendisse in est. Congue mauris rhoncus aenean
                    vel elit scelerisque. Cursus in hac habitasse platea
                    dictumst quisque sagittis. Vestibulum mattis ullamcorper
                    velit sed ullamcorper morbi tincidunt ornare. Laoreet sit
                    amet cursus sit amet dictum sit. Augue ut lectus arcu
                    bibendum. Vulputate ut pharetra sit amet aliquam id diam
                    maecenas ultricies. Et magnis dis parturient montes.
                    Eleifend mi in nulla posuere sollicitudin aliquam. Tellus in
                    metus vulputate eu scelerisque felis imperdiet proin. Amet
                    nulla facilisi morbi tempus iaculis urna id. Cras semper
                    auctor neque vitae tempus quam.
                  </p>
                  <p className="size-14 color-tex">
                    Etiam sit amet nisl purus in mollis. Amet dictum sit amet
                    justo donec. Fringilla phasellus faucibus scelerisque
                    eleifend donec. Tortor posuere ac ut consequat semper. Sit
                    amet volutpat consequat mauris nunc congue nisi vitae
                    suscipit. Gravida rutrum quisque non tellus orci ac auctor
                    augue. Ultrices gravida dictum fusce ut. Scelerisque varius
                    morbi enim nunc faucibus. Morbi tempus iaculis urna id.
                    Rutrum tellus pellentesque eu tincidunt tortor.
                  </p>
                </div>
              </div>
              {/* End.content-comp */}
            </section>
          </div>
        </div>
        {/* ===================================
START THE SIDEBAR MENU - CONNECTED MODAL
    ==================================== */}
       
        {/* ===================================
START THE SIDEBAR MENU - guest MODAL
    ==================================== */}
       
        {/* ===================================
START STATUS CONNECTION
    ==================================== */}
        <div className="d-flex justify-content-center">
          <div
            className="toast status-connection"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          />
        </div>
        <div className="scrollTop">
          {/* RIGHT - DEFAULT */}
          <button type="button" className="btn scroll-top">
            <i className="ri-arrow-drop-up-line" />
          </button>
          {/* CENTER */}
          <button type="button" className="btn scroll-top --center">
            <i className="ri-arrow-drop-up-line" />
          </button>
          {/* LEFT */}
          <button type="button" className="btn scroll-top --left">
            <i className="ri-arrow-drop-up-line" />
          </button>
        </div>
        {/* JS FILES */}
        {/* PWA APP SERVICE REGISTRATION AND WORKS JS */}
      </>

      <Script src="assets/vendors/zuck_stories/zuck.min.js"></Script>
      <Script src="assets/vendors/smoothscroll/smoothscroll.min.js"></Script>
      <Script src="assets/vendors/swiper/swiper-bundle.min.js"></Script>
      <Script src="assets/vendors/nouislider/nouislider.min.js"></Script>
      <Script src="assets/vendors/nouislider/wNumb.min.js"></Script>
      <Script src="assets/js/bootstrap.bundle.min.js"></Script>
      <Script src="assets/js/pwa-services.js"></Script>
      <Script src="assets/js/custom.js"></Script>
    </>
  );
}
