import Head from "next/head";
import Image from "next/image";

import Script from "next/script";



export default function Home() {
  return (
    <>
      <Head>
        <title>Cre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
         
      </Head>

      <>
        {/* ===================================
START LODAER PAGE
    ==================================== */}
        
        {/* START WRAPPER */}
        <div id="wrapper">
          {/* START CONTENT */}
          <div id="content">
            {/* ===================================
        START THE HEADER
      ==================================== */}
            <header className="default heade-sticky">
              <div className="un-title-page go-back">
                <a href="app-components.html" className="icon">
                  <i className="ri-arrow-drop-left-line" />
                </a>
              </div>
            </header>
            {/* ===================================
        START THE SPACE STICKY
      ==================================== */}
            <div className="space-sticky" />
            {/* ===================================
         START THE CONTENT
      ==================================== */}
            <section className="un-page-components">
              <div className="un-title-default">
                <div className="text">
                  <h2>Toasts</h2>
                  <p>
                    Push notifications to your visitors with a toast, a
                    lightweight and easily customizable alert message.
                    <code className="d-block">data-bs-delay="5000"</code>
                    Delay hiding the toast (ms)
                  </p>
                </div>
              </div>
              <div className="content-comp p-0 mb-4">
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Toast Container with icon
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastOne"
                    >
                      Top
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Toast Full with icon <code>-full</code>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastTwo"
                    >
                      Top
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Hide the toast manually
                      <code className="d-block">data-bs-autohide="false"</code>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastThree"
                    >
                      Top
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Full Shadow Toast <br />
                      <span className="size-13 color-text">
                        add <code>.--shadowfull</code> to
                        <code>.toast</code>
                      </span>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastFour"
                    >
                      Top
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text pe-2">
                    <h2 className="m-0 size-15 weight-500">
                      Background color orange
                      <br />
                      <span className="size-13 color-text">
                        Change <code>.bg-orange</code> to{" "}
                      </span>
                      <code>.bg-red</code> <code>.bg-blue</code>{" "}
                      <code>.bg-dark</code> <code>.bg-pink</code>
                      <code>.bg-yellow</code>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastFive"
                    >
                      Top
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Position : bottom
                      <br />
                      <span className="size-13 color-text">
                        <code>.place__bottom</code>
                      </span>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastSix"
                    >
                      Bottom
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Position : bottom Full Width
                      <br />
                      <span className="size-13 color-text">
                        <code>.place__bottom, .-full</code> <br />
                        add class <code>.fullscreen, .env-pb</code> to{" "}
                        <code>.toast</code>
                      </span>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastSeven"
                    >
                      Bottom
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Position : Center
                      <br />
                      <span className="size-13 color-text">
                        <code>.place__center</code> <br />
                      </span>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastEight"
                    >
                      Center
                    </button>
                  </div>
                </div>
                <div className="space-items" />
                {/* un-title-default */}
                <div className="un-title-default py-3">
                  <div className="text">
                    <h2 className="m-0 size-15 weight-500">
                      Position : Center Auto Width
                      <br />
                      <span className="size-13 color-text">
                        add class <code>.w-auto</code> to <code>.toast</code>
                        <br />
                      </span>
                    </h2>
                  </div>
                  <div className="un-block-right">
                    <button
                      type="button"
                      className="btn btn-md-size bg-primary text-white rounded-pill"
                      id="btnToastTen"
                    >
                      Center
                    </button>
                  </div>
                </div>
              </div>
              {/* End.content-comp */}
            </section>
          </div>
        </div>
        {/* ===================================
START THE TOASTS
    ==================================== */}
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__top w-100"
        >
          <div
            id="liveToastOne"
            className="toast --shadow"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={3000}
          >
            <div className="toast-body">
              <div className="icon color-blue">
                <i className="ri-information-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>Update your profile.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-blue"
                  >
                    Go to Settings
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__top -full w-100"
        >
          <div
            id="liveToastTwo"
            className="toast --shadow fullscreen"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={5000}
          >
            <div className="toast-body">
              <div className="icon color-orange">
                <i className="ri-alert-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>Complete your profile.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-orange"
                  >
                    Go to Settings
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__top -full w-100"
        >
          <div
            id="liveToastThree"
            className="toast --shadow fullscreen"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="false"
          >
            <div className="toast-body">
              <div className="icon color-green">
                <i className="ri-shield-check-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>Payment completed successfully.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-green"
                  >
                    Go to Settings
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__top w-100"
        >
          <div
            id="liveToastFour"
            className="toast --shadowfull"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={3000}
          >
            <div className="toast-body">
              <div className="icon color-red">
                <i className="ri-error-warning-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>The operation failed.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-red"
                  >
                    Update Payment Method
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__top w-100"
        >
          <div
            id="liveToastFive"
            className="toast bg-orange"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={3000}
          >
            <div className="toast-body">
              <div className="icon color-red">
                <i className="ri-error-warning-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>The operation failed.</p>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__bottom w-100"
        >
          <div
            id="liveToastSix"
            className="toast --shadowfull"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={3000}
          >
            <div className="toast-body">
              <div className="icon color-red">
                <i className="ri-error-warning-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>The operation failed.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-red"
                  >
                    Update Payment Method
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__bottom -full w-100"
        >
          <div
            id="liveToastSeven"
            className="toast --shadowfull fullscreen env-pb"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={5000}
          >
            <div className="toast-body">
              <div className="icon color-green">
                <i className="ri-checkbox-circle-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>The operation failed.</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-green"
                  >
                    Update Payment Method
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__center w-100"
        >
          <div
            id="liveToastEight"
            className="toast bg-dark"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={5000}
          >
            <div className="toast-body">
              <div className="icon color-green">
                <i className="ri-checkbox-circle-fill" />
              </div>
              <div className="content">
                <div className="display__text">
                  <p>Added successfully</p>
                  <a
                    href="page-edit-profile.html"
                    className="display-link color-green"
                  >
                    Update Payment Method
                  </a>
                </div>
              </div>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="toast"
                aria-label="Close"
              >
                <i className="ri-close-fill" />
              </button>
            </div>
          </div>
        </div>
        <div
          aria-live="polite"
          aria-atomic="true"
          className="d-flex justify-content-center place__center w-100"
        >
          <div
            id="liveToastTen"
            className="toast bg-dark w-auto"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
            data-bs-autohide="true"
            data-bs-delay={1000}
          >
            <div className="toast-body">
              <div className="content">
                <div className="display__text">
                  <p>Added successfully</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE SIDEBAR MENU - CONNECTED MODAL
    ==================================== */}
     
        {/* ===================================
START THE SIDEBAR MENU - guest MODAL
    ==================================== */}
       
        {/* ===================================
START STATUS CONNECTION
    ==================================== */}
        <div className="d-flex justify-content-center">
          <div
            className="toast status-connection"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          />
        </div>
        {/* JS FILES */}
        {/* PWA APP SERVICE REGISTRATION AND WORKS JS */}
      </>

      <Script src="assets/vendors/zuck_stories/zuck.min.js"></Script>
      <Script src="assets/js/toast.js"></Script>
      <Script src="assets/vendors/smoothscroll/smoothscroll.min.js"></Script>
      <Script src="assets/vendors/swiper/swiper-bundle.min.js"></Script>
      <Script src="assets/vendors/nouislider/nouislider.min.js"></Script>
      <Script src="assets/vendors/nouislider/wNumb.min.js"></Script>
      <Script src="assets/js/bootstrap.bundle.min.js"></Script>
      <Script src="assets/js/pwa-services.js"></Script>
      <Script src="assets/js/custom.js"></Script>
    </>
  );
}
