import Head from "next/head";
import Image from "next/image";

import Script from "next/script";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <section className="bg-gradient-started">
          <div className="bg-noise" />
        </section>

        <div id="wrapper">
          <div id="content">
            <header className="default heade-sticky bg-transparent header-light">
              <div className="un-item-logo">
                <a href="index.html">
                  <img
                    className="logo-img"
                    src="images/logo-white.svg"
                    alt=""
                  />
                </a>
              </div>
              <div className="un-block-right">
                {/* menu-sidebar */}
                <div className="menu-sidebar">
                  <button
                    type="button"
                    name="sidebarMenu"
                    aria-label="sidebarMenu"
                    className="btn"
                    data-bs-toggle="modal"
                    data-bs-target="#mdllSidebar-connected"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width={19}
                      height="9.3"
                      viewBox="0 0 19 9.3"
                    >
                      <g
                        id="Group_8081"
                        data-name="Group 8081"
                        transform="translate(-329 -37)"
                      >
                        <rect
                          id="Rectangle_3986"
                          data-name="Rectangle 3986"
                          width={19}
                          height="2.3"
                          rx="1.15"
                          transform="translate(329 37)"
                          fill="#222032"
                        />
                        <rect
                          id="Rectangle_3987"
                          data-name="Rectangle 3987"
                          width={19}
                          height="2.3"
                          rx="1.15"
                          transform="translate(329 44)"
                          fill="#222032"
                        />
                      </g>
                    </svg>
                  </button>
                </div>
              </div>
            </header>

            



            <section className="un-info-template">
              <div className="main-img-nft">
                <picture>
                  <source
                    srcSet="images/other/3d_nfts.webp"
                    type="image/webp"
                  />
                  <img src="images/other/3d_nfts.png" alt="nft picture" />
                </picture>
              </div>
              <div className="block-numbers">
                <div className="pages">
                  <h2>45+</h2>
                  <p>Page Packs</p>
                </div>
                <div className="dividar-y" />
                <div className="components">
                  <h2>98+</h2>
                  <p>Components</p>
                </div>
              </div>
            </section>
            {/* ===================================
        START PAGES LIST
      ==================================== */}
            <section className="un__listPages_started margin-t-30">
              <div className="content">
                <div className="title">
                  <h3>Unic - NFT Marketplace</h3>
                  <p>
                    We Include <span>Creativity</span> and{" "}
                    <span>Professionalism</span> in Our Modern Pages for Ready
                    Use.
                  </p>
                </div>
                <div className="un-navMenu-default style_glass px-0">
                  <ul className="nav">
                    <li className="nav-item">
                      <a href="app-pages.html" className="nav-link background">
                        <div className="item-content-link">
                          <div className="icon">
                            <img src="images/icons/icon_page.png" alt="" />
                          </div>
                          <h3 className="link-title">Page Packs</h3>
                        </div>
                        <div className="other-cc">
                          <span className="badge-text">+45</span>
                          <div className="icon-arrow">
                            <i className="ri-arrow-drop-right-line" />
                          </div>
                        </div>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="app-homes.html" className="nav-link">
                        <div className="item-content-link">
                          <div className="icon">
                            <img src="images/icons/icon_homes.png" alt="" />
                          </div>
                          <h3 className="link-title">Unic. Homes</h3>
                        </div>
                        <div className="other-cc">
                          <span className="badge-text xs-badge">3</span>
                          <div className="icon-arrow">
                            <i className="ri-arrow-drop-right-line" />
                          </div>
                        </div>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="app-components.html" className="nav-link">
                        <div className="item-content-link">
                          <div className="icon">
                            <img
                              src="images/icons/icon_components.png"
                              alt=""
                            />
                          </div>
                          <h3 className="link-title">Components</h3>
                        </div>
                        <div className="other-cc">
                          <span className="badge-text">+98</span>
                          <div className="icon-arrow">
                            <i className="ri-arrow-drop-right-line" />
                          </div>
                        </div>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </section>
            {/* ===================================
        START THE SOME FEATURES
      ==================================== */}
            <section className="un_features_list">
              <div className="content">
                <ul>
                  <li>
                    <div className="icon bg-green text-white">
                      <i className="ri-command-line" />
                    </div>
                    <h4>Structured Files</h4>
                    <p>Find what you're looking for with structured files.</p>
                  </li>
                  <li>
                    <div className="icon bg-blue text-white">
                      <i className="ri-switch-fill" />
                    </div>
                    <h4>PWA Ready</h4>
                    <p>Add to the home screen and use it as an app.</p>
                  </li>
                  <li>
                    <div className="icon bg-pink text-white">
                      <i className="ri-artboard-2-line" />
                    </div>
                    <h4>Easy to Customize with Sass</h4>
                    <p>
                      We are using Sass for CSS. You can change colors, sizes on
                      single file.
                    </p>
                  </li>
                  <li>
                    <div className="icon bg-orange text-white">
                      <i className="ri-stack-line" />
                    </div>
                    <h4>Bootstrap 5 - Vanilla JS</h4>
                    <p>You do not need to use jQuery</p>
                  </li>
                  <li>
                    <div className="icon bg-secondary text-white">
                      <i className="ri-toggle-line" />
                    </div>
                    <h4>Dark Mode is Awesome</h4>
                    <p>Turn dark theme on and off with the switch</p>
                  </li>
                </ul>
              </div>
            </section>
            {/* ===================================
        START THE FOOTER - BUTTONS
      ==================================== */}
            <section className="bloack-get-started">
              <div className="un-navMenu-default p-0">
                <ul className="nav">
                  <li className="nav-item">
                    <a
                      href="https://themeforest.net/item/unic-nft-mobile-template/36083774"
                      target="_blank"
                      className="nav-link bg-transparent"
                    >
                      <div className="item-content-link">
                        <div className="icon text-white">
                          <i className="ri-shopping-bag-3-fill" />
                        </div>
                        <h3 className="link-title text-white">
                          Get Unic. Today
                        </h3>
                      </div>
                      <div className="other-cc">
                        <span className="badge-text">$24</span>
                        <div className="icon-arrow">
                          <i className="ri-arrow-drop-right-line" />
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a href="homepage.html" className="nav-link bg-primary">
                      <div className="item-content-link">
                        <div className="icon text-white">
                          <i className="ri-home-5-fill" />
                        </div>
                        <h3 className="link-title text-white">Let's Start</h3>
                      </div>
                      <div className="other-cc">
                        <span className="badge-text text-white" />
                        <div className="icon-arrow text-white">
                          <i className="ri-arrow-drop-right-line" />
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </section>
            {/* ===================================
        START THE COPYRIGHT
      ==================================== */}
            <section className="copyright-mark">
              <div className="content">
                <img
                  className="logo-gray"
                  src="images/logo-gray.svg"
                  alt="image"
                />
                <p>Copyright © Unic 2022</p>
              </div>
            </section>
          </div>
        </div>
        {/* ===================================
START THE MODAL UPLOAD
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllUploadItem"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Upload Item</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item text-center">
                  <p>
                    Choose <span>"Single"</span> if you want your collectible to
                    be one of a kind or
                    <span>"Multiple"</span>
                    if you want to sell one collectible multiple times
                  </p>
                  <div className="grid_buttonUpload">
                    <a
                      href="page-create-single.html"
                      className="btn btn-create bg-primary text-white margin-b-20"
                    >
                      Create Single
                    </a>
                    <a
                      href="page-create-multi.html"
                      className="btn btn-create bg-white border border-solid border-snow text-dark"
                    >
                      Create Multiple
                    </a>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL ADD ETH
    ==================================== */}
        <div
          className="modal transition-bottom screenFull defaultModal mdlladd__rate fade"
          id="mdllAddETH"
          tabIndex={-1}
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h1 className="title-modal">Add ETH to your wallet</h1>
                <button
                  type="button"
                  className="btn btnClose"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <i className="ri-close-fill" />
                </button>
              </div>
              <div className="modal-body">
                <div className="content-upload-item">
                  <p className="text-center">
                    Select one of the options to deposit <br /> ETH to your
                    wallet
                  </p>
                  <div className="un-navMenu-default margin-t-30 p-0">
                    <ul className="nav flex-column">
                      <li className="nav-item mb-3">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-exchange-box-line" />
                            </div>
                            <h3 className="link-title">
                              Deposit from an exchange
                            </h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                      <li className="nav-item mb-0">
                        <a
                          className="nav-link effect-click"
                          href="javascript: void(0)"
                        >
                          <div className="item-content-link">
                            <div className="icon color-text w-auto">
                              <i className="ri-bank-card-line" />
                            </div>
                            <h3 className="link-title">Buy with card</h3>
                          </div>
                          <div className="other-cc">
                            <span className="badge-text" />
                            <div className="icon-arrow">
                              <i className="ri-arrow-drop-right-line" />
                            </div>
                          </div>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="modal-footer border-0">
                <div className="env-pb" />
              </div>
            </div>
          </div>
        </div>
        {/* ===================================
START THE MODAL SIDEBAR MENU - CONNECTED
    ==================================== */}
        
        
       
        
        <div className="d-flex justify-content-center">
          <div
            className="toast status-connection"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          />
        </div>
        
      </>
      
    </>
    
  );
}


